name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Your default branch is 'master', not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install pandas --system

      - name: Run data processing scripts
        run: |
          chmod +x build.sh
          # Run the build script with Python directly instead of using uv run
          sed -i 's/uv run/python/g' build.sh
          ./build.sh

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # The folder containing your site files
          branch: gh-pages  # The branch to deploy to
